# Tabuada
nome = str(input('Olá, digite seu nome:'))
print('Legal, {}, Então você tem dificuldades com a tabuada?'.format(nome))
n1 = int(input('Digite a tabuada que você tem dificuldade:'))
print('Sério!! {}, você não sabe essa tabuada, é muito fácil!'.format(nome))
print('{} x {} = {}'.format(n1, 1, n1*1))
print('{} x {} = {}'.format(n1, 2, n1*2))
print('{} x {} = {}'.format(n1, 3, n1*3))
print('{} x {} = {}'.format(n1, 4, n1*4))
print('{} x {} = {}'.format(n1, 5, n1*5))
print('{} x {} = {}'.format(n1, 6, n1*6))
print('{} x {} = {}'.format(n1, 7, n1*7))
print('{} x {} = {}'.format(n1, 8, n1*8))
print('{} x {} = {}'.format(n1, 9, n1*9))
print('{} x {} = {}'.format(n1, 10, n1*10))
print('Viu como é fácil, agora vê se estuda e não fica dependendo de máquinas para resolver!!!')
